# Generated by Django 3.2.12 on 2022-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artikel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='title',
            field=models.TextField(),
        ),
    ]
