# Generated by Django 3.2.12 on 2022-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_account_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
