# Generated by Django 3.2.12 on 2022-03-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_account_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
