# Generated by Django 3.2.12 on 2022-03-15 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_artikel_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('artikel_creator_username', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_creator_username', models.CharField(blank=True, max_length=200, null=True)),
                ('id_forum', models.CharField(blank=True, max_length=200, null=True)),
                ('artikel_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.artikel')),
                ('comment_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
