# Generated by Django 3.2.12 on 2022-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
